ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE rides ADD COLUMN IF NOT EXISTS category VARCHAR(30) NOT NULL DEFAULT 'transfer';
ALTER TABLE rides ADD COLUMN IF NOT EXISTS stops TEXT DEFAULT '[]';

ALTER TABLE quotes ADD COLUMN IF NOT EXISTS category VARCHAR(30) NOT NULL DEFAULT 'transfer';
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS stops TEXT DEFAULT '[]';

